feat(-interface): Prefix dimension and attribute names
ecbsdmx/t2swdc pull request #66
Opened 2016-12-15 22:37 UTC by airosa

Prefix dimension names with key position and attributes names with M.

Closes #50

2016-12-16 08:31 UTC, Tzaphkiel requested changes
Please review the comments, I believe there might be an error in the components prefix.

2016-12-16 08:31 UTC, Tzaphkiel commented on src/util/wdc-interface.coffee
> +            prefix = if keyPos < 10 then "0#{keyPos}" else "keyPos"
I think this might be an error, the `else` should read: `"#{keyPos}"` no?

2016-12-16 08:31 UTC, Tzaphkiel commented on test/util/wdc-interface.test.coffee
>      checkResult = () ->
If the above is an error, the test should then be modified to check for positional elements `> 10`.

2016-12-19 21:24 UTC, airosa commented on src/util/wdc-interface.coffee
> +            prefix = if keyPos < 10 then "0#{keyPos}" else "keyPos"
Yep

2016-12-19 21:39 UTC, airosa commented on test/util/wdc-interface.test.coffee
>      checkResult = () ->
Yep

2016-12-20 09:54 UTC, Tzaphkiel approved these changes

2016-12-20 09:54 UTC, merged